---
title: "That's my type"
---

In the following exercises, first guess what type the vector will be coerced to, then check your intuition with the `typeof()` function.

1.  `c(1, 1L, "C")`

```{r}
#| label: view-1
c(1, 1L, "C")
```

```{r}
#| label: help-1
1
1L
"C"
```

Guess: \_\_\_

```{r}
#| label: check-1
#typeof(c(1, 1L, "C"))
```

2.  `c(1L / 0, "A")`

```{r}
#| label: view-2
# add code here
```

```{r}
#| label: help-2
# add code here
```

Guess: \_\_\_

```{r}
#| label: check-2
# add code here
```

3.  `c(1:3, 5)`

```{r}
#| label: view-3
# add code here
```

```{r}
#| label: help-3
# add code here
```

Guess: \_\_\_

```{r}
#| label: check-3
# add code here
```

4.  `c(3, "3+")`

```{r}
#| label: view-4
# add code here
```

```{r}
#| label: help-4
# add code here
```

Guess: \_\_\_

```{r}
#| label: check-4
# add code here
```

5.  `c(NA, TRUE)`

```{r}
#| label: view-5
# add code here
```

```{r}
#| label: help-5
# add code here
```

Guess: \_\_\_

```{r}
#| label: check-5
# add code here
```
